### ISSUE TITLE
Leave confirmation

### ISSUE THREAD

**Issue by jstawik** [kubafilinger/driver-reaction-time-tester#1]
It would be useful to popup a leave confirmation, onbeforeunload style, when a user wants to leave the page after hitting the "Start simulation" button but before hitting "Save"
I'm pretty sure we lost some results that way

**Comment by kubafilinger** [comment]
Functionality has been added in this commit:
https://github.com/kubafilinger/driver-reaction-time-tester/commit/1a069df737210f6c454ac81d1efbaaf24f7e5c9f
